export const GET_ALL_FILES_START = 'GET_ALL_FILES_START';
export const GET_ALL_FILES_SUCCESS = 'GET_ALL_FILES_SUCCESS';
export const GET_ALL_FILES_ERROR = 'GET_ALL_FILES_ERROR';

export const UPLOAD_FILE_START = 'UPLOAD_FILE_START';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const UPDATE_FILE_START = 'UPDATE_FILE_START';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const UPDATE_FILE_ERROR = 'UPDATE_FILE_ERROR';

export const DELETE_FILE_START = 'DELETE_FILE_START';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_ERROR = 'DELETE_FILE_ERROR';

export const GEN_PDF_START = 'GEN_PDF_START';
export const GEN_PDF_SUCCESS = 'GEN_PDF_SUCCESS';
export const GEN_PDF_ERROR = 'GEN_PDF_ERROR';